---
title: "Make a Plot"
author: "Kieran Healy"
date: "10-January-2020"
output:
  pdf_document: default
  html_document: default
---

## Load Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gapminder)
library(here)
library(tidyverse)
library(socviz)
library(haven)
library(sjlabelled)

```


## Tidy Data

```{r 03-make-a-plot-1}

```

```{r import stata file}
# Import Stata, SPSS, and SAS file by using `haven` package
findata <- read_dta(file = "Data/micro_world.dta")

class(findata)

# Show all variables in the first 10 observations by using `tidyverse` package 
# or sometime library(tibble), which function `as_tibble()`
show(findata)

# Remember that when we import the dataset from Stata, the labels will also be
# imported, we need install and use a package called `sjlabelled` to show labels. 
get_label(findata)

# Or get_label(x = findata), create an object 

# Variable label is too long to display in R, we can call to display only 
# the variable that we want to see only 
get_label(findata$emp_in)
get_label(findata$female)

# We can remove label of a specific variable or all of them
femaledata <- remove_label(findata$female)

get_label(femaledata)

fdata <- remove_all_labels(findata)

# Or use this function `fdata <- remove_label(findata)`
get_label(fdata)

# At the same time, we want to remove value label 


# write_dta(data = findata , path = "Data/findata.dta")


library(survey)
library(srvyr)


options(survey.lonely.psu = "adjust")
options(na.action="na.pass")

gss_wt <- subset(findata, age >30) %>%
    mutate(stratvar = interaction(age, pop_adult)) %>%
    as_survey_design(ids = wpid_random,
                     strata = stratvar,
                     weights = wgt,
                     nest = TRUE)

out_grp <- gss_wt %>%
    filter(age %in% seq(30, 60, by = 4)) %>%
    group_by(age, educ, fin2) %>%
    summarize(prop = survey_mean(na.rm = TRUE))

out_grp

out_mrg <- gss_wt %>%
    filter(year %in% seq(1976, 2016, by = 4)) %>%
    mutate(racedeg = interaction(race, degree)) %>%
    group_by(year, racedeg) %>%
    summarize(prop = survey_mean(na.rm = TRUE))

out_mrg


out_mrg <- gss_wt %>%
    filter(year %in% seq(1976, 2016, by = 4)) %>%
    mutate(racedeg = interaction(race, degree)) %>%
    group_by(year, racedeg) %>%
    summarize(prop = survey_mean(na.rm = TRUE)) %>%
    separate(racedeg, sep = "\\.", into = c("race", "degree"))

out_mrg


```
## Mappings link data to things you see

```{r 03-make-a-plot-2}
findata$educ
```


```{r 03-make-a-plot-3}
p <- ggplot(data = findata)
```

```{r 03-make-a-plot-4}
p <- ggplot(data = findata,
            mapping = aes(x = educ,
                          y = regionwb))
```

## Mappings link data to things you see

```{r 03-make-a-plot-2}
gapminder
```



```{r 03-make-a-plot-3}
p <- ggplot(data = gapminder)
```


```{r 03-make-a-plot-4}
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
```


```{r 03-make-a-plot-5, fig.cap='This empty plot has no geoms.', fig.width=8, fig.height=5}
p
```

```{r 03-make-a-plot-6, fig.cap='A scatterplot of Life Expectancy vs GDP', fig.width=8, fig.height=5}
p + geom_point() 
```


## Build your plots layer by layer

```{r 03-make-a-plot-7, fig.cap='Life Expectancy vs GDP, using a smoother.', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y=lifeExp))
p + geom_smooth()

```

```{r 03-make-a-plot-8, fig.cap='Life Expectancy vs GDP, showing both points and a GAM smoother.', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y=lifeExp))
p + geom_point() + geom_smooth() 

```

```{r 03-make-a-plot-9, fig.cap='Life Expectancy vs GDP, points and an ill-advised linear fit.', fig.width=8, fig.height=5}
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y=lifeExp))
p + geom_point() + geom_smooth(method = "lm") 
```


```{r 03-make-a-plot-10, fig.cap='Life Expectancy vs GDP scatterplot, with a GAM smoother and a log scale on the x-axis.', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y=lifeExp))
p + geom_point() +
    geom_smooth(method = "gam") +
    scale_x_log10()

```

```{r 03-make-a-plot-11, fig.cap='Life Expectancy vs GDP scatterplot, with a GAM smoother and a log scale on the x-axis, with better labels on the tick marks.', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder, mapping = aes(x = gdpPercap, y=lifeExp))
p + geom_point() +
    geom_smooth(method = "gam") +
    scale_x_log10(labels = scales::dollar)
```


## Mapping aesthetics vs setting them

```{r 03-make-a-plot-12, fig.cap='What has gone wrong here?', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = "purple"))
p + geom_point() +
    geom_smooth(method = "loess") +
    scale_x_log10()
```


```{r 03-make-a-plot-13, fig.cap='Setting the color attribute of the points directly.', fig.width=8, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point(color = "purple") +
    geom_smooth(method = "loess") +
    scale_x_log10()
```

```{r 03-make-a-plot-14, fig.cap='Setting some other arguments.', fig.width=8, fig.height=5, fig.margin=TRUE}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp)) 
p + geom_point(alpha = 0.3) +
    geom_smooth(color = "orange", se = FALSE, size = 8, method = "lm") +
    scale_x_log10()
```


```{r 03-make-a-plot-15, fig.cap='A more polished plot of Life Expectancy vs GDP.', fig.width=8, fig.height=5.25, layout = 'l-page'}

p <- ggplot(data = gapminder, mapping = aes(x = gdpPercap, y=lifeExp))
p + geom_point(alpha = 0.3) + geom_smooth(method = "gam") +
    scale_x_log10(labels = scales::dollar) +
    labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")
```



```{r 03-make-a-plot-16, fig.cap='Mapping the continent variable to the color aesthetic.', fig.width=8.5, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = continent))
p + geom_point() +
    geom_smooth(method = "loess") +
    scale_x_log10()
```

```{r 03-make-a-plot-17, fig.cap='Mapping the continent variable to the color aesthetic, and correcting the error bars using the fill aesthetic.', fig.width=8.5, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = continent,
                          fill = continent))
p + geom_point() +
    geom_smooth(method = "loess") +
    scale_x_log10()
```

## Aesthetics can be mapped per geom

```{r 03-make-a-plot-18, fig.cap='Mapping aesthetics on a per-geom basis. Here color is mapped to continent for the points but not the smoother.', fig.width=8.5, fig.height=5}

p <- ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp))
p + geom_point(mapping = aes(color = continent)) +
    geom_smooth(method = "loess") +
    scale_x_log10()
```


```{r 03-make-a-plot-19, fig.cap='Mapping a continuous variable to color.', out.width="100%", fig.width=8.5, fig.height=5}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point(mapping = aes(color = log(pop))) +
    scale_x_log10()    
```

## Save your work

```{r knitopt, echo = TRUE, eval = FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
```


```{r 03-make-a-plot-20, echo=TRUE, eval=FALSE}
ggsave(filename = "figures/my_figure.png")
```


```{r 03-make-a-plot-21}
here() 
```

#```{r 03-make-a-plot-22}

#p_out <- p + geom_point(mapping = aes(color = log(pop))) +
 #   scale_x_log10()

#ggsave(here("figures", "lifexp_vs_gdp_gradient.pdf"), plot = p_out)

#ggsave(here("figures", "lifexp_vs_gdp_gradient.png"), plot = p_out)
```



